############################################################
# Dockerfile to build MySQL Base Container
# Based on: centos:centos7
# DATE: 10/29/2015
# Author: Alex Yin - name@example.com
# COPYRIGHT: Centling Technologies Co.Ltd.
############################################################

# Set the base image
FROM mysql:5.6

#File Author /Maintainer
MAINTAINER Alex YIN <mooncreeks@gmail.com>
